### ISSUE TITLE
Summary: Exceeds Expectations

### ISSUE THREAD

**Issue by melissamcewen** [JanDW/webAPI-from-scratch#1]
Hi, I'm reviewing this for codecademy. Great job on this project! Everything works great and it's clear you have learned a lot.

I have a few minor pointers I'll file as issues.

Good attempt at the YAML implementation. If you want to finish that, there are many versions of this project on Github that can show you the way. Here is one: https://github.com/dmorrish/CE-BackEndAPI-Project-3

Otherwise, I hope you're excited for the capstone! You're ready for it!

**Comment by JanDW** [comment]
Thanls. I finished the YAML implementation shortly after I submitted, I think the issue was that I assigned the loaded YAML to the `database` variable, rather than having the function return it as an object. That's what it told me to do in the instructions, but i didn't quite register. Once I did that it seems to work.
